### ISSUE TITLE
uncertanty of parameters

### ISSUE THREAD

**Issue by qwertyinme** [jasperbok/4chan-image-downloader#1]
Hey uh, could you please specify the exact parameters necessary to download the images?

You see the issue at hand is: "what board should I download from?" -/b/ "number?" -thread number-
"0 images found"

and no matter the board or variation on the spelling I can't get it to work.
And it's not the thread number either because not only can I ping it but I can open the thread in an archive...

so what am I doing wrong?

With regards:
-qwerty.

**Comment by jasperbok** [comment]
I just tried it, and it appears 4chan has added some anti-scraping measures in the last 7 years since I wrote this script :)

When the script runs it receives an error page stating that it is blocked based on the browser signature.

So yeah, this is not going to work without rewriting (parts of) the script. Sorry about that! I'll add a note in the readme to prevent future disappointment as I probably won't take the time to fix this old thing.

Sorry to disappoint you :(
